name: flutter_reader
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.5.4 #适配
  flutter_easyrefresh: ^2.2.1
  flutter_easyloading: ^3.0.5
  flutter_swiper_view: ^1.1.8 #轮播图
  dio: ^4.0.6 #网络请求
  flutter_staggered_grid_view: ^0.6.2 #瀑布流
  shared_preferences: ^2.0.15 #本地储存历史记录
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  webview_flutter: ^3.0.4
  flutter_html: ^3.0.0-alpha.6 #html
  pin_code_fields: ^7.4.0 #验证码
  city_pickers: ^1.1.3 # 城市
  crypto: ^3.0.2
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_cropper: ^7.0.5
  android_id: ^0.0.7
  pull_to_refresh: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MyIcon   #字体名自己定义
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: userIcon
      fonts:
        - asset: assets/fonts/userIconfont.ttf
  assets:
#    - assets/images/banner.png
